### ISSUE TITLE
Disable auto-inserting vendor prefixes in Stylus

### ISSUE THREAD

**Issue by einarlove** [sergeche/emmet-sublime#421]
Since all CSS preprocessors give you an option to let them handle vendor prefixes for you, I thought it would be simple to disable all the vendor prefixes that comes from emmet snippets and abbreviations. That wasn't the case.

I came over `autoInsertVendorPrefixes` in a tweet, but it was set on `css.autoInsertVendorPrefixes: false`, but I wanted it disabled only on Stylus files.

I tried in Emmet.sublime-settings

``` javascript
{
  "preferences": {
    "stylus.valueSeparator": ": "
    "stylus.autoInsertVendorPrefixes": false
  }
}
```

but it just disabled all of emmet for stylus.

Came over https://github.com/emmetio/emmet-docs/issues/26 where you described a complicated way to disable it globally, but that seems like quite the hazel.

Is there another way, or have I missed something?
##

**Comment by Kout** [comment]
Kind of workaround is setting `caniuse.era` in user preferences file to value `e1` (near future ‒ see [Emmet docs](http://docs.emmet.io/customization/preferences/)). As the above mentioned setting to disable vendor prefixes did not work for me (ST3, Linux Mint 16.04), this helped. At least I got rid of annoying 
```
display: -webkit-flex;
display: -moz-flex;
display: -ms-flex;
display: flex;
```
stack after expanding  `df` :) . In days of autoprefixer unnecessary help.

**Comment by 4knort** [comment]
i made a folder in c:/users/my-user-name
a folder called emmet
i placed a file in this folder called preferences.json
here an object in it
```
{
  "css.autoInsertVendorPrefixes": false,
  "less.autoInsertVendorPrefixes": false,
  "scss.autoInsertVendorPrefixes": false,
  "sass.autoInsertVendorPrefixes": false,
  "caniuse.enabled": false,
  "caniuse.vendors": false
}
```

anyway i've got prefixes on everything
