### ISSUE TITLE
css rule order question

### ISSUE THREAD

**Issue by s10wen** [sergeche/emmet-sublime#533]
Firstly @sergeche thanks so much for you work with Emmet, I use it everyday!

I'm wondering how the order is decided for css rules. For example in ST currently:
```
c = cursor
f = font
p = position
```

I think that it would be nice for Emmet defaults to use more popular css properties e.g.
```
c = color
f = float
p = padding
```

I'm wondering if there would be any drawbacks for other people if this was the case? I'm guessing I could always customise my Emmet config, but I'm thinking this might be useful for other people?

**Comment by andismith** [comment]
I agree, using the properties above would be more clear. It does mean the defaults would change though.

I wonder if there's any way to see how many people customise their Emmet config to use these values, and what other values they change?

**Comment by sergeche** [comment]
There’s a similar discussion: https://github.com/emmetio/emmet/pull/121
Closing this issue to move discussion there

**Comment by s10wen** [comment]
I found a simple solution for this and created a gist, here are mine so far:
https://gist.github.com/s10wen/b2c839e725965ad11c1f
