### ISSUE TITLE
Conflicts with SublimeCodeIntel

### ISSUE THREAD

**Issue by hbprotoss** [sergeche/emmet-sublime#538]
It seems emmet conflicts with SublimeCodeIntel when editing HTML files. 

`div.container>div.row` will expand to `div.container><div class="row"></div>` when I input the characters one by one. But if I paste the statement from clipboard, it works well.

After disable SublimeCodeIntel, everything's fine,  no matter if input one by one or paste for clipboard.

Please help

**Comment by sergeche** [comment]
Try to play with CodeIntel settings,for example, exclude HTML syntax from completions list: https://github.com/SublimeCodeIntel/SublimeCodeIntel/blob/master/SublimeCodeIntel.sublime-settings

**Comment by hbprotoss** [comment]
What if I want both the code completion from SublimeCodeIntel(AngularJS directive) and emmet? Any ideas?

**Comment by sergeche** [comment]
You should contact with CodeInter developer regarding this issue. Or use `Ctrl+E` to expand abbreviations
