### ISSUE TITLE
Ctrl+E conflict with OSX system hotkey (OSX+SublimeText2)

### ISSUE THREAD

**Issue by WilliamYoung** [sergeche/emmet-sublime#543]
In OSX, Ctrl+E means goto the end of a line. It is important for OSX & EMACS users, please consider change another hotkey.

**Comment by sergeche** [comment]
https://github.com/sergeche/emmet-sublime/blob/master/CONTRIBUTING.md

**Comment by denizdogan** [comment]
I really think you should reconsider this issue. The default behavior is basically broken on OSX, it's like deciding that the "End" key is a good key to rebind.
