### ISSUE TITLE
jc не разворачивается в justify-content

### ISSUE THREAD

**Issue by in-in** [sergeche/emmet-sublime#545]
`jc` не разворачивается в `justify-content: ;`
Нажимаю tab и получаю `color: #000;`

С остальными сокращениями связаными с flexbox тоже самое. 
Я что-то делаю не так?

ST: Build 3083
OS: Ubuntu 14.04 (mint 17.1)
##

**Comment by sergeche** [comment]
В ST пока устаревшая версия ядра без этих сниппетов
