### ISSUE TITLE
How to disable Emmet attempting to expand a particular string?

### ISSUE THREAD

**Issue by benfrain** [sergeche/emmet-sublime#546]
Looking at the read me and I see "disabled_single_snippet_for_scopes" and in threads I have seen "disabled_single_snippets": "space separated list of tags goes here"

However, I'm not quite sure how to implement these. I basically want Emmet to stop trying to expand the string `/**`, specifically in CSS/SCSS.

What would be the corrent syntax to add to Emmet.sublime-settings? Thanks for any guidance.

**Comment by bluedusk** [comment]
I'm having issues with the:
`"disable_tab_abbreviations": true`
and
` "disabled_single_snippet_for_scopes":"text.html" `
I want Emmet to stop expand the 'html' tag in html file,not working.

**Comment by sergeche** [comment]
@benfrain Emmet never expands `/**` because it’s invalid abbreviation.
@bluedusk https://github.com/sergeche/emmet-sublime/blob/master/Emmet.sublime-settings#L65

**Comment by benfrain** [comment]
@sergeche this is odd. I am using DocBlockr (https://github.com/spadgos/sublime-jsdocs/) and it dosn't expand `/**` in Sass/CSS. However, when I disable Emmet it works perfectly. Is there any part of Emmet that would be interfering?

**Comment by sergeche** [comment]
@benfrain  Can you record a small video/gif with this bug?

**Comment by benfrain** [comment]
Updated comment but sure, will record a GIF

**Comment by sergeche** [comment]
That’s make sense: unlike HTML, in CSS etc. Emmet completely overrides Tab key so it’s not even passed further. There’s no easy solution because Sublime Text API does not allow passing key event from one plugin to another.

PS: I’m using DocBlockr too, in my case simply pressing Enter key after `/**` creates full comment block.

**Comment by benfrain** [comment]
Ah!!!! I've been a fool :) Yes, just pressing Enter will work fine for me, thanks.

**Comment by bluedusk** [comment]
THe only setting works for me is add 
`"disable_tab_abbreviations": true`
in sublime setting. 
Any setting i made in Emmet setting won't work. Any idea why? thanks.

**Comment by sergeche** [comment]
Did you changed `Emmet.sublime-settings` or `Preferences.sublime-settings`?
