### ISSUE TITLE
JSX support in Sublime Text 3?

### ISSUE THREAD

**Issue by falzhobel** [sergeche/emmet-sublime#548]
Hi,

Just saw the tweet about [.jsx support](https://twitter.com/emmetio/status/583398878789132289), tried it in Sublime Text 3 and tags aren't expanding when I try it within a React render method. I'm using the `JavaScript (Babel)` syntax, could that be the reason it's not working? Do we have to write the render method in a specific way with a specific syntax to make it work?

Thanks!

**Comment by rashthedude** [comment]
+1

**Comment by sergeche** [comment]
I assume you’re trying to use Tab key: https://github.com/sergeche/emmet-sublime#tab-key-handler

**Comment by harrisgeo** [comment]
+1

**Comment by jeroveoo** [comment]
+2

**Comment by falzhobel** [comment]
@sergeche Indeed that was the problem, using `ctrl+e` works fine and changes `span.bar` as `<span className="bar"></span>` for example.

Just to make sure, there is really no way of having the tab completion?

Thanks again for the amazing work on Emmet, can't live without it :wink:

**Comment by sergeche** [comment]
You can enable it as described in link above, but you’ll loose your native JS snippets

**Comment by falzhobel** [comment]
Alright, well using `ctrl-e` is good enough, thanks for the help!

**Comment by e2goon** [comment]
+1
