### ISSUE TITLE
Input ending with a number doesn't expand on TAB

### ISSUE THREAD

**Issue by isaacalves** [sergeche/emmet-sublime#560]
Emmet does not expand my input if it ends with a number.

For example, the following inputs will not expand when I hit TAB.

`h1`
`div.col-md-4`
`div.a2`

I'm using ST3

**Comment by sergeche** [comment]
Make sure you’ve set document syntax to HTML

**Comment by isaacalves** [comment]
Solved: the Emmet package was actually not installed! (only Emmet CSS Snippets) But before throwing things at me please care to explain why the auto complete was working anyway (except for that situation where the user text input ended with a number)
