### ISSUE TITLE
Does Rename Tag still work?

### ISSUE THREAD

**Issue by entozoon** [sergeche/emmet-sublime#568]
Say I have a line of code:
```
<div>foo</div>
```
I want to be able to highlight the two occurrences of 'div' so as to change the tag.
It looks like it should be the Rename Tag shortcut - Shift+Ctrl+'  but that does nothing for me in Sublime 3 and there are no keyboard conflicts (checked with FindKeyConflicts).

Has the feature been removed.. or.. changed.. or some other crazy issue?

**Comment by sergeche** [comment]
Try to call this action from Command Palette. It’s not removed, should be in Emmet

**Comment by entozoon** [comment]
Not to sound too dumb but.. how do I do that?
ctrl-shift-p and typing rename brings up nothing..

I've also tried adding this to my sublime keymap with no joy:
```
{ "keys": ["ctrl+alt+q"], "command": "rename_tag"},
```

**Comment by sergeche** [comment]
Can you post your ST log here?

**Comment by entozoon** [comment]
Actually there might be no need - I removed a plugin "AutoFileName" which had some errors and I can now see the command in the palette!

To change the keyboard shortcut, it looks like I'll have to record a macro as in this thread:
https://github.com/sergeche/emmet-sublime/issues/439

Thank you for your help sergeche, very quick debugging help!
