### ISSUE TITLE
Overrides auto complete commit

### ISSUE THREAD

**Issue by OliverJAsh** [sergeche/emmet-sublime#577]
Sublime provides an auto completion menu, and when you press tab to commit the selected entry in this menu, Emmet conflicts with this and overrides the behaviour. i.e.

![image](https://cloud.githubusercontent.com/assets/921609/10221605/53f0ffc0-6847-11e5-824d-c9e53fc29dc8.png)

Pressing tab here will result in `<main></main>`

**Comment by sergeche** [comment]
https://github.com/sergeche/emmet-sublime#tab-key-handler

**Comment by OliverJAsh** [comment]
Will disable and use Ctrl-E instead.

**Comment by sergeche** [comment]
You can also check out this option: https://github.com/sergeche/emmet-sublime/blob/master/Preferences.sublime-settings#L29
