### ISSUE TITLE
Tab expansion stopped working

### ISSUE THREAD

**Issue by SuneRadich** [sergeche/emmet-sublime#578]
Yesterday I could use Tab Expansion in Sublime Text 3 without any issues, and have been using it for months. But today, it stopped working. I have not changed any settings whatsoever.

I can see that there was an update yesterday, and figure that it has something to do with that update. I was however not aware that Sublime Text 3 would auto update plugins?

Did something about tabexpansion change in the latest version?

**Comment by sergeche** [comment]
Try to restart Sublime Text and check ST console for errors

**Comment by idavidmcdonald** [comment]
Came across the same issue. Restarting Sublime fixed it

**Comment by ivancucer** [comment]
Yeah, it's really strange. After restarting ST, this problem disappeared... The console shows no errors.

**Comment by xiansheng** [comment]
Same issue with jade in ST3. And stylus in Bracket

**Comment by SuneRadich** [comment]
Restarting Sublime did indeed help with the issue.
