### ISSUE TITLE
В Jade не работает tab

### ISSUE THREAD

**Issue by xiansheng** [sergeche/emmet-sublime#580]
Пишу ul>li*3>a{item}
Не срабатывает, а ставит просто пробел
Попробовал https://github.com/emmetio/emmet/issues/406#issuecomment-151144075
ну у меня также как у парня, который оставил этот скриншот http://joxi.ru/DrlaB97uLPMlmP
Сижу на Windows, ST3. ставил с package control. 
Раньше работало как надо

**Comment by sergeche** [comment]
Проблема в в последних изменениях в Jade. Запушил обновление

**Comment by markup-pro** [comment]
Добрый день!
почему - то перестал работать jade.
пишу input, просто ставит пробел и все.
И так со всем остальным
