### ISSUE TITLE
Emmet not working because one or more packages

### ISSUE THREAD

**Issue by MichelZaal85** [sergeche/emmet-sublime#595]
Today I came across something so Awesome, that the only thought in my brain was, Need!
So I installed Emmet. The only problem I now have, is that it's not working.. I think it's because
of 1 or more packages that I have installed. 

I've tested the **emmet** package also on a clean(er) installation of ST, and it worked like a charm. 

_The part that's not working is the:
.row>.large-...>.panel> ...._

I have the following list of packages installed in my ST;

- AngularJS
- AutoFileName
- AutoHotKey
- AutoSpell
- CSS snippets
- DiffView
- **Emmet (Not working)**
- File Navigator
- FileBrowser
- Find ++
- Git
- Google Spell Check
- JS Snippets
- JSHint
- JSLint
- JSON Reindent
- Monokai JSON+
- Open
- Open in Default Application
- PyV8
- Sass
- SASS Build
- SideBarEnhancements
- Sublime-GitHub
- SublimeTextGitx

I have some other installed packages, but those are disabled at the moment. 
Is there one or more package that prevents my **emmet** from working?

**Comment by sergeche** [comment]
Check out ST console for errors, you can post its contents here

**Comment by MichelZaal85** [comment]
Dear Sergeche,

Thank you for you reply. Personally I don't see any errors in the (standard ctrl+`) console log.
This is the response of my console after starting ST:

``DPI scale: 1``
``startup, version: 3083 windows x64 channel: stable``
``executable: /C/Sublime Text 3/sublime_text.exe``
``working dir: /C/Sublime Text 3``
``packages path: /D/Sublime Text 3 Portable/Data/Packages``
``state path: /D/Sublime Text 3 Portable/Data/Local``
``zip path: /D/Sublime Text 3 Portable/Packages``
``zip path: /D/Sublime Text 3 Portable/Data/Installed Packages``
``ignored_packages: [ Ignored Packages ]``
``pre session restore time: 0.91365``
``warning: mnemonic t not found in menu caption Tools``
``startup time: 1.24565``
``first paint time: 1.26465``
``reloading plugin [... All Plugins ...]``
``plugins loaded``
``Building AutoSpell Index: Started``
``Building AutoSpell Index: Finished``
``Emmet: No need to update PyV8``
``Package Control: No updated packages``

**Comment by sergeche** [comment]
Did you set document syntax to HTML?

**Comment by MichelZaal85** [comment]
Dear Sergeche,

Yes, I did.

**Comment by sergeche** [comment]
Does it work with Ctrl+E? Do you see autocomplete popup when pressing Tab key?

**Comment by MichelZaal85** [comment]
Dear Sergeche,

No, I don't see any auto-complete options. Ctrl+E says (in the status bar) copied find string from buffer
and Ctrl+Space (to activate auto-complete in my ST) tells me, no auto-completion available. 

Is it possible that my version of ST is not compatible with the emmet package?

**Comment by sergeche** [comment]
Can we connect via TeamViewer so I can see it by myself?

**Comment by MichelZaal85** [comment]
Dear Sergeche,

Sure, the only problem at the moment is that I do not have the time to set up TeamVier. At the moment I have little time plus I haven't installed TeamV.. right now.  

If that aright with you, I'll set up TeamVier later this day and reply to this message.

**Comment by MichelZaal85** [comment]
Dear Sergeche,

If you like I can set up the Team-viewer to show you.

**Comment by Nevitones** [comment]
Please, How was this solved ?

**Comment by rebotak** [comment]
any solution for this?

**Comment by sergeche** [comment]
The issue was that Ctrl-E keybinding was was bound to incorrect action name in user config. Removing such binding resolved issue.

**Comment by rebotak** [comment]
aaah, mine was solved with this solution:

1.  Exit SublimeText 3
2. Rename or move the `Installed Packages` file called `0_package_control_loader.sublime-package to 0_package_control_loader.sublime-package` into anything or anywhere for backups..
>for ubuntu its in:``/home/*username*/.config/sublime-text-3/Installed Packages/0_package_control_loader.sublime-package``

3. Open SublimeText 3, and do the emmet shortcut (ctrl+e or tab).

**Comment by AkshayIyer12** [comment]
@rebotak Thanks a lot worked like a charm

**Comment by mikob** [comment]
@rebotak worked for me too. But why!? What!?

**Comment by tylercollier** [comment]
When I followed the advice from rebotak, after restarting Sublime Text, a modal dialog said:

> Package Control
>
> 2 missing dependencies were just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.

Whether I tried CTRL+E right away or after restarting Sublime Text (again), I still got `copied find string from buffer`.

@rebotak Can you explain how you knew to do that and what the `0_package_control_loader.sublime-package ` file does?
