### ISSUE TITLE
more  intelligence needed for "script" abbreviation 

### ISSUE THREAD

**Issue by zzzgit** [sergeche/emmet-sublime#603]
if i don't install **emmet-sublime**,and type `script` in the html document,and then type `tab`,it will be expended to `<script type="text/javascript"></script>`
now i install this plugin,and do the same thing,it will be expended to `<script></script>`
this is ridiculous

**Comment by sergeche** [comment]
What’s ridiculous? `type="text/javascript"` is not required for `<script>` tag

**Comment by zzzgit** [comment]
`type="text/javascript"` is what most people want to get by default

**Comment by sergeche** [comment]
Do you have any public stats that prove your point of view?
Anyway, you can customize Emmet as you want: https://github.com/sergeche/emmet-sublime#extensions-support

**Comment by zzzgit** [comment]
`C:\Users\hotmail.com\AppData\Roaming\Sublime Text 3\Packages\Emmet`,i can't find this folder in explorer,why why why?
only `C:\Users\hotmail.com\AppData\Roaming\Sublime Text 3\Packages\` exist.
