### ISSUE TITLE
self defined snippets don't work

### ISSUE THREAD

**Issue by zzzgit** [sergeche/emmet-sublime#610]
```javascript
{
"snippets":{
		"html": {
			"abbreviations": {
				"script": "<script type=\"text/javascript\"></script>",
				"bb":"<aa>${class}</aa>",
				"style":"<style type=\"text/css\"></style>"
			}
		},
		"javascript":{
			"abbreviations": {
				"getvar": "var v='a variable';"
			}
		}
	}
}
```

i have set some snippets in the user config file
the abbreviations in html file work well
but the abbreviations in js files don't work
what is wrong?

**Comment by zzzgit** [comment]
i have solved it

**Comment by zzzgit** [comment]
i made an mistake to set this issue to closed

**Comment by Wangbaogang** [comment]
i have the same problem width you, the second problem. Now do you know why it happened?

**Comment by Wangbaogang** [comment]
,,,,,

**Comment by Wangbaogang** [comment]
it works just now. i am careless...
