### ISSUE TITLE
XSL completion stopped working after ST3 removed the XSL filetype

### ISSUE THREAD

**Issue by crewone** [sergeche/emmet-sublime#611]
The XSL filetype has been removed in ST3. Forever. It's not coming back. It's just XML now.

Since then, XSL specific completions like "tn" and "for" have stopped working. 

I've gotten quite attached to Emmet and it's XSL shortcuts. Is there a way we can make them work again?

**Comment by sergeche** [comment]
You can copy XSL snippets into XML syntax profile as a part of [Emmet customization](http://docs.emmet.io/customization/)

**Comment by crewone** [comment]
WBond just created a user-installable XSL language that also enables Emmet to work as it used to.

https://packagecontrol.io/packages/XSL
