### ISSUE TITLE
Tab Completion not working for certain combinations

### ISSUE THREAD

**Issue by JamesRiall** [sergeche/emmet-sublime#628]
Tab completion is only partially working in ST3. For some combinations it works fine - 'div>ul>li*7' for example works as expected. 'div>h1+p doesn't work' though, and only expands the p, resulting in 'div>h1+<p></p>'. I can't seem to get the '+' operator to work at all. Also, a simple div>h1 only expands the h1, but not the div. I've tried uninstalling and reinstalling+restart also, manually installing PyV8 but no joy. This is what my console gives:

startup, version: 3114 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/jamesriall/Library/Application Support/Sublime Text 3/Packages
state path: /Users/jamesriall/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/jamesriall/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.983397
using gpu buffer for window
startup time: 1.04608
first paint time: 1.0725
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin Alignment.Alignment
reloading plugin All Autocomplete.all_views_completions
reloading plugin AutoFileName.autofilename
reloading plugin AutoFileName.getimageinfo
reloading plugin BracketGuard.BracketGuard
reloading plugin Clickable URLs.clickable_urls
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin CSS3.css3_completions
reloading plugin CSS3.rgb_to_hex
reloading plugin Delete Lines.delete_lines
reloading plugin Emmet.emmet-plugin
reloading plugin Git.git_commands
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_change
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_helper
reloading plugin GitGutter.view_collection
reloading plugin Hayaku - tools for writing CSS faster.__init__
reloading plugin Hayaku - tools for writing CSS faster.hayaku_dict_driver
reloading plugin Hayaku - tools for writing CSS faster.hayaku_get_merged_dict
reloading plugin Hayaku - tools for writing CSS faster.hayaku_probe
reloading plugin Hayaku - tools for writing CSS faster.hayaku_sublime
reloading plugin Hayaku - tools for writing CSS faster.hayaku_sublime_contexts
reloading plugin Hayaku - tools for writing CSS faster.hayaku_sublime_cycling
reloading plugin Hayaku - tools for writing CSS faster.hayaku_sublime_get_options
reloading plugin Hayaku - tools for writing CSS faster.hayaku_sublime_navigation_commands
reloading plugin Hayaku - tools for writing CSS faster.hayaku_templates
reloading plugin Highlight Whitespaces.highlight_whitespaces
reloading plugin HTML5.encode_html_entities
reloading plugin HTML5.html_completions
reloading plugin HTMLBeautify.HTMLBeautify
reloading plugin JsFormat.js_formatter
reloading plugin Material Theme.mt_activator
reloading plugin Material Theme.mt_changes
reloading plugin Material Theme.mt_config
reloading plugin Material Theme.mt_info
reloading plugin Material Theme.mt_urls
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin RSpec.OpenRSpecFile
reloading plugin RSpec.RSpecCreateModule
reloading plugin RSpec.RSpecDetectFileType
reloading plugin RSpec.shared
reloading plugin SassBeautify.SassBeautify
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-contrib-htmlhint.linter
SublimeLinter: htmlhint linter loaded 
reloading plugin SublimeLinter-csslint.linter
SublimeLinter: csslint linter loaded 
reloading plugin SublimeLinter-html-tidy.linter
SublimeLinter: htmltidy linter loaded 
reloading plugin SublimeLinter-jshint.linter
SublimeLinter: jshint linter loaded 
reloading plugin SublimeLinter-jsxhint.linter
SublimeLinter: jsxhint linter loaded 
reloading plugin SublimeLinter-ruby.linter
SublimeLinter: ruby linter loaded 
reloading plugin TrailingSpaces.trailing_spaces
reloading plugin Trimmer.Trimmer
reloading plugin WordHighlight.word_highlight
reloading plugin Autoprefixer.Autoprefixer
reloading plugin Autoprefixer.node_bridge
reloading plugin Babel.Babel
reloading plugin BeautifyRuby.beautify_ruby
reloading plugin Cheat Sheets.cheat-sheets
reloading plugin CodeFormatter.CodeFormatter
CodeFormatter: formatting python files on ST3 not supported.
reloading plugin ColorPicker.sublimecp
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin IntelliDocs.intellidocs
reloading plugin JSHint Gutter.JSHint
reloading plugin SublimeCodeIntel.ordereddict
reloading plugin SublimeCodeIntel.SublimeCodeIntel
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: off 
CodeFormatter: Plugin Initialized
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2016-08-14 09:29:14, next run at 2016-08-14 10:29:14 or after
SublimeLinter: jshint activated: /usr/local/bin/jshint 
SublimeLinter: csslint activated: /usr/local/bin/csslint 
SublimeLinter: htmlhint activated: /usr/local/bin/htmlhint 
SublimeLinter: htmltidy activated: /usr/local/bin/tidy 
+ Info: processing `HTML': please wait...
Could not import subprocess32 module, falling back to subprocess module

**Comment by sergeche** [comment]
https://github.com/sergeche/emmet-sublime#tab-key-handler
