### ISSUE TITLE
Add Pug support (ex Jade)

### ISSUE THREAD

**Issue by werty1001** [sergeche/emmet-sublime#643]
Hi, **Jade** is **Pug** now and snippets / abbreviations not work for it.

**Comment by zhekaus** [comment]
+1
Emmet doesn't work inside pug files yet ((

**Comment by utopiafx** [comment]
I need this also to work in sublime. For codepen it works with plug!
How could it be config/done with sublime?

**Comment by Bumboy** [comment]
Same problem here.

I saw a user of youtube that uses emmet with pug, I do not understand why it does not work for me, only works con VScode, but not in atom, sublime text and brackets. I have already installed emmet and pug addons.

**Comment by F1ks3r** [comment]
same problem

**Comment by aarontyree** [comment]
need pug support. PUG! PUG! PUG! PUG! #notmyemmet

**Comment by syampolskiy** [comment]
I have to use Jade syntax in Pug files to make Emmet work correctly.
when will you fix this problem?
thx

**Comment by amaurycatelan** [comment]
Hello there, I have an unapproved [pull request](https://github.com/sergeche/emmet-sublime/pull/654) about this issue. 
I make some steps to fix it. I hope this helps. :smiley:

1. **Remove Original Package:**

Package Control `Cmd+Shift+P` or `Ctrl+Shift+P `
Package Control: `Remove Package`
Find and remove `Emmet`

2. **Find your Package Folder:**

In OSX the path is:
`˜/Library/Application Support/Sublime Text 3/Packages`

(in ST, find `Browse Packages`) - [more](http://docs.sublimetext.info/en/latest/basic_concepts.html#the-packages-directory)

3. **Install Manually:**

from: official repository with my pull request [#654](https://github.com/sergeche/emmet-sublime/pull/654)

- `git clone git@github.com:sergeche/emmet-sublime.git`
- `git fetch origin pull/654/head:pull/654`
- `git checkout pull/654`

**or**

from: my personal repository

- `git clone git@github.com:amaurycatelan/emmet-sublime.git -b feature/support-pug`

4. **Syntax highlighting (extra)**

Go to your Package Folder (step 2)  and run:
`git clone git@github.com:davidrios/pug-tmbundle.git Pug`

5. **Restart Sublime Text**
You'll probably need to `restart Sublime` after installation for the changes to take effect.

**Comment by amaurycatelan** [comment]
Cool, its merged! Thanks again @sergeche :tada: :raised_hands:

**Comment by werty1001** [comment]
@amaurycatelan @sergeche Thanks!

**Comment by nicothin** [comment]
Can you please tell me how to set up Emmet to use BEM with live abbreviation mode for Pug?
In the HTML, I call the live mode (Ctrl+Shift+Enter) and enter `.block>._elem`
As a result, I get:
```
<div class="block">
  <div class="block__elem"></div>
</div>
```
But in pug it does not work, I get:
```
.block
  ._elem //- there must be .block__elem
```
I suspect that this is configurable, but how?
My current settings:
```
"snippets": {
    "html": {
      "filters": "html, bem"
    },
    "pug": {
      "filters": "pug, bem", // failure, it does not work
    }
  }
```

**Comment by werty1001** [comment]
@nicothin Try set `"filters": "bem, jade"` or use [bempug](https://github.com/werty1001/bempug) / [bemto](https://github.com/kizu/bemto)

**Comment by nicothin** [comment]
@werty1001 
`"filters": "bem, jade"` — It works as I need it
Many thanks!

**Comment by evgeniyproweb** [comment]
Hi, after installation Pug on sublime 3 it doesn't want compiling(dont create html file), in the settings i added -->> "filename_filter": "pug"
P.S. sometimes i dont want to use phpstorm if the project is Landing(1 page)
