### ISSUE TITLE
some expansions do not work as expected

### ISSUE THREAD

**Issue by deepak** [sergeche/emmet-sublime#647]
`li*3` expands to three li tags. works as expected.
`li{TODO}` expands to one li tab with content. works as expected. 
`li.post$*3` expands to three li tags with incrementing classes. works as expected.

`li*3{TODO}` does not expand to anything
`li.post$*3{TODO$}` expands to one li tag with content. `<li class="post1">TODO1</li>`. but expected three

**Comment by sergeche** [comment]
Should be `li{TODO}*3` because you multiply `li{TODO}` three times
