### ISSUE TITLE
JSX detection

### ISSUE THREAD

**Issue by borela** [sergeche/emmet-sublime#680]
I wrote a [syntax that covers the new javascript features + JSX (FJSX15)](https://github.com/borela/naomi) and because I highlight JSX tags using the root scope `text.html.basic.jsx` or `text.html.jsx` _(this was necessary to support many color schemes so that if they don't have rules targeting JSX, it would be highlighted as HTML)_, the tags are being expanded as if it were HTML.

After investigating a bit, I think this [line](https://github.com/sergeche/emmet-sublime/blob/master/editor.js#L374) is responsible for detecting JSX and adding `text.html.jsx` there would solve it.

**Comment by borela** [comment]
Changed the syntax root.

**Comment by kud** [comment]
Did it work? Because I'm able to change a html tag into jsx but not a Component via cmd+shift+k. Nothing happens on a component.

However cmd+d works.

(and I use Naomi)
