### ISSUE TITLE
SCSS Autocomplete & Line Breaks w/ Sublime

### ISSUE THREAD

**Issue by tr1s** [sergeche/emmet-sublime#686]
I like having tab for expanding emmet abbreviations, **but I want to use Enter for expanding CSS/SCSS suggestions/autocomplete. How can I make this so?** I used to have it but setup I reset my sublime and forgot what I did. Right now enter just line breaks. I can't find a fix in the docs.

Help me out please and thanks!

**Comment by sergeche** [comment]
Currently, Emmet doesn’t work as autocomplete provider for Sublime. There’s a new Emmet 2.0 beta available for Atom and VS Code thats works like that
