### ISSUE TITLE
Expansion of php tab to <php></php> isn't expected

### ISSUE THREAD

**Issue by praveenscience** [sergeche/emmet-sublime#687]
Hi @sergeche,

I would like to reference the [issue](https://github.com/sergeche/emmet-sublime/issues/10#issuecomment-8623228) here. I am not sure if this is totally closed, but let me tell you what happened.

I am using Sublime Text 2 and both Mac and Windows for the past two years without any problems. Today I did the following:

1. Bought a new MacBook Pro 2017 model.
2. Installed Sublime Text 2.
3. Installed Package Control.
4. Installed Emmet (along with Emmet Css Snippets and EmmetOneLine).
5. Opened a new file and set the syntax to PHP (but ST2 was showing me HTML).
6. Typed `php` and gave a tab, it expanded to `<php></php>`.

This issue isn't there in my Windows or MacBook Pro 2015. Only the new Mac has this problem. What is different and what should I do to make `php` and tab key to give me `<?php | ?>`? Thanks in advance.

**Comment by sergeche** [comment]
Please check README

**Comment by praveenscience** [comment]
Alright... :)
