### ISSUE TITLE
expansion is moved to the right by two characters

### ISSUE THREAD

**Issue by morales2k** [sergeche/emmet-sublime#698]
I have 

`img.newStrip`

which upon expanding with tab OR ctrl+e I get the following:

`im<img src="" alt="" class="newStr">`

'im' from 'img' stays outside tag, and it cuts 'Strip' to only 'Str'. Cursort is placed where exected, within the src quotes... but the class name ends up botched and two characters are ignored in the expansion process....

This is using ST3 3.1.1 b3176, latest version of this package as per st3 package control, (I removed it, and added it again - then restarted editor) and using it on a Laravel Blade syntax php file.

Please advise if there's any additional info I can pass along.

I must add that there are no error messages in the console.

**Comment by sergeche** [comment]
Please make sure your document syntax is set to HTML. Also you can check out ST log for errors

**Comment by morales2k** [comment]
Normally, it used to work for this syntax, as early as this morning. 

I can confirm the syntax package had no upgrades recently. 

I have to add, another quirky thing that just happened.

if I do this:

`div.col-md-6*2`

And select the entire text and hit `ctrl-e` it will expand properly without stripping two characters to the right. 

But it doesn't do it twice as expected when using `*2`

**Comment by sergeche** [comment]
Maybe it’s an issue with ST beta? Have you tried on stable channel?

**Comment by morales2k** [comment]
This is the console output during the last 30 or so minutes during which the issue has ocurred a number of times. 
[st3.log](https://github.com/sergeche/emmet-sublime/files/2070112/st3.log)

I have more errors on other packages unrelated to Emmet.... not sure if that would affect it if I have some issues with Sublime Linter.... seems unlikely...

**Comment by morales2k** [comment]
I don't even know whether or not I'm on beta/stable channel... where can I find an indicator of such?

**Comment by sergeche** [comment]
Can’t see any Emmet errors. Can you check in stable ST3?

**Comment by morales2k** [comment]
I think I am in the stable version.... 
![image](https://user-images.githubusercontent.com/1074855/40945890-9a6003aa-6828-11e8-9175-ca23cdf8f018.png)
