### ISSUE TITLE
Sublime Text 3: Emmet doesn't show custom tag on tab

### ISSUE THREAD

**Issue by jippy89** [sergeche/emmet-sublime#708]
### What I wanted to do
1. Write 'b-row'
2. Press tab!
**< b-row > < /b-row >**

### What it do
1. Write 'b-row'
2. Press tab!
**b-row** 

Basically just the usual tab. Other tags like html, h1, etc works
However, when I do _b-row[input="wow"],_ it shows up like this
**< b-row input="wow" >< /b-row >**

**Sublime Text 3 Version:** Build 3176
**OS:** Windows 64-bit

**P.S.**
This came up to my console..

> Emmet: No need to update PyV8
> Package Control: Skipping automatic upgrade, last run at 2018-12-13 10:07:03, next run at 2018-12-13 11:07:03 or after
> Unable to open /C/Users/CP/AppData/Roaming/Sublime Text 3/Packages/Emmet/Emmet.sublime-settings
> Unable to open /C/Users/CP/AppData/Roaming/Sublime Text 3/Packages/Emmet/Default (Windows).sublime-keymap

But when I try to upgrade packages using Package Control, and trying to upgrade the packages, it says "There are no packages ready for upgrade." Does it have anything to do with that?

**Comment by sergeche** [comment]
In case of single element, Tab key works for known tags only, otherwise it will replace any work with tag, event if you try to use native Sublime Text snippets. You should either use <kbd>Ctrl-E</kbd> shortcut or update Tab key handler: https://github.com/sergeche/emmet-sublime#tab-key-handler

**Comment by jippy89** [comment]
Thanks for replying, it works fine as I wanted now.
